"""Generate the LaTeX tables that carry numbers, from the committed JSON, so no
value is typed by hand. Run from the paper directory."""
import json, math
MAN = json.load(open('data/MANIFEST.json'))
MAT = json.load(open('data/MATRIX.json'))

order = ['1efs','1BNA','dna_acgt','2KOC','rna_acgu','1UBQ','5PTI','peptide','tax9','1HHK','1F7Y']
pretty = {'1efs':'1efs','1BNA':'1BNA','dna_acgt':'d(ACGT)','2KOC':'2KOC','rna_acgu':'r(ACGU)',
          '1UBQ':'1UBQ','5PTI':'5PTI','peptide':'ACE-AGSV-NME','tax9':'Tax 11--19','1HHK':'1HHK','1F7Y':'1F7Y'}
desc = {
 '1efs':'DNA:RNA hybrid, model 1 of PDB 1EFS; carries the term-by-term comparison',
 '1BNA':'Drew--Dickerson dodecamer d(CGCGAATTCGCG), B-DNA duplex',
 'dna_acgt':'DNA 4-mer, one of each base, free $5^\\prime$-OH and $3^\\prime$-OH',
 '2KOC':'UUCG tetraloop RNA hairpin, model 1 of PDB 2KOC',
 'rna_acgu':'RNA 4-mer, one of each base, free $5^\\prime$-OH and $3^\\prime$-OH',
 '1UBQ':'Ubiquitin, $\\beta$-grasp fold',
 '5PTI':'BPTI, three disulfide bonds',
 'peptide':'Capped tetrapeptide, four residue kinds, built extended',
 'tax9':'HTLV-1 Tax nonamer LLFGYPVYV, capped, free in solution',
 '1HHK':'HLA-A*02:01, $\\beta_2$-microglobulin and the bound Tax nonamer',
 '1F7Y':'Ribosomal protein S15 bound to a 16S rRNA fragment',
}
ffs = {}
for c in MAT:
    ffs.setdefault(c['system'], []).append(c['force_field'])

with open('tables/systems.tex','w') as f:
    f.write('% generated by make_tables.py from systems/MANIFEST.json and energies/MATRIX.json\n')
    f.write('\\begin{tabular}{@{}llrrp{3.1cm}p{4.5cm}@{}}\n\\toprule\n')
    f.write('System & Class & Atoms & Chains & Force fields compared & What it tests \\\\\n\\midrule\n')
    for s in order:
        m = MAN[s]
        f.write(f"{pretty[s]} & {m['class'].replace('Protein, ','protein, ').replace('Protein-','protein--').replace('Terminal control','terminal control').replace('Heteroduplex','heteroduplex').replace('DNA duplex','DNA duplex').replace('RNA hairpin','RNA hairpin')} & {m['atoms']:,} & {len(m['chains'])} & {', '.join(ffs[s])} & {desc[s]} \\\\\n")
    f.write('\\bottomrule\n\\end{tabular}\n')

def fmt(v):
    return '--' if v is None else f"{v:.6f}"
def dfmt(v, m):
    if v is None: return '--'
    d = v - m
    s = f"{d:+.6f}"
    return s

with open('tables/matrix.tex','w') as f:
    f.write('% generated by make_tables.py from energies/MATRIX.json\n')
    f.write('\\begin{tabular}{@{}llrrrrrrr@{}}\n\\toprule\n')
    f.write(' & & \\multicolumn{4}{c}{Total energy (kcal/mol)} & \\multicolumn{3}{c}{Reference minus MOSAICS (kcal/mol)} \\\\\n')
    f.write('\\cmidrule(lr){3-6}\\cmidrule(lr){7-9}\n')
    f.write('System & Force field & MOSAICS & sander & OpenMM & GROMACS & sander & OpenMM & GROMACS \\\\\n\\midrule\n')
    last=None
    for s in order:
        for c in [c for c in MAT if c['system']==s]:
            name = pretty[s] if s!=last else ''
            last=s
            f.write(f"{name} & {c['force_field']} & {fmt(c['mosaics'])} & {fmt(c['sander'])} & {fmt(c['openmm'])} & {fmt(c['gromacs'])} & {dfmt(c['sander'],c['mosaics'])} & {dfmt(c['openmm'],c['mosaics'])} & {dfmt(c['gromacs'],c['mosaics'])} \\\\\n")
    f.write('\\bottomrule\n\\end{tabular}\n')

# summary statistics used in the text, printed for the claim check
gaps=[]; within=0; within4=0; ncomp=0; nref2=0
for c in MAT:
    refs=[c[k] for k in ('sander','openmm','gromacs') if c[k] is not None]
    g=[abs(r-c['mosaics']) for r in refs]
    ncomp+=len(g)
    if len(refs)>=2: nref2+=1
    gaps.append(max(g))
    if max(g)<=0.001: within+=1
    if max(g)<=0.0004: within4+=1
gaps.sort()
print('cells',len(MAT),'comparisons',ncomp,'cells with >=2 refs',nref2)
print('within 0.001:',within,' within 0.0004:',within4)
print('median largest gap', gaps[len(gaps)//2] if len(gaps)%2 else (gaps[len(gaps)//2-1]+gaps[len(gaps)//2])/2)
print('min largest gap',gaps[0],'max',gaps[-1])
print('systems',len({c['system'] for c in MAT}),'ff labels',len({c['force_field'] for c in MAT}))
